# Generated by Django 3.1 on 2020-08-31 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id_doador', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do doador')),
                ('email_doador', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail do doador')),
                ('senha', models.CharField(blank=True, max_length=100, null=True)),
                ('imagem', models.FileField(blank=True, null=True, upload_to='perfil_doador/%Y/%m/%d/')),
            ],
            options={
                'verbose_name_plural': 'Doadores',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id_endereco', models.AutoField(primary_key=True, serialize=False)),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Numero_Contato',
            fields=[
                ('id_numero', models.AutoField(primary_key=True, serialize=False)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ong',
            fields=[
                ('id_ong', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da ong')),
                ('email_ong', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail da ong')),
                ('senha', models.CharField(blank=True, max_length=100, null=True)),
                ('imagem', models.FileField(blank=True, null=True, upload_to='perfil_ong/%Y/%m/%d/')),
                ('Numero_Contato', models.ManyToManyField(to='doacoes.Numero_Contato')),
                ('id_endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacoes.endereco')),
            ],
            options={
                'verbose_name_plural': 'Ongs',
            },
        ),
        migrations.CreateModel(
            name='Publicacao_Ong',
            fields=[
                ('id_publicacao_Ong', models.AutoField(primary_key=True, serialize=False)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='Publicacao_ong/%Y/%m/%d/')),
                ('id_ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacoes.ong')),
            ],
            options={
                'verbose_name_plural': 'Publicações_Ongs',
            },
        ),
        migrations.CreateModel(
            name='Publicacao_Doador',
            fields=[
                ('id_publicacao_doador', models.AutoField(primary_key=True, serialize=False)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='Publicacao_doador/%Y/%m/%d/')),
                ('id_doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacoes.doador')),
            ],
            options={
                'verbose_name_plural': 'Publicações_Doadores',
            },
        ),
        migrations.AddField(
            model_name='doador',
            name='Numero_Contato',
            field=models.ManyToManyField(to='doacoes.Numero_Contato'),
        ),
        migrations.AddField(
            model_name='doador',
            name='id_endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacoes.endereco'),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id_chat', models.AutoField(primary_key=True, serialize=False)),
                ('mensagem', models.CharField(blank=True, max_length=500, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacoes.doador')),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacoes.ong')),
            ],
        ),
    ]
