# Generated by Django 3.1.2 on 2020-11-01 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id_doador', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=100, verbose_name='CPF')),
                ('nome', models.CharField(max_length=100, null=True, verbose_name='Nome do Doador')),
                ('email_doador', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail do Doador')),
                ('senha', models.CharField(blank=True, max_length=100, null=True)),
                ('imagem', models.FileField(blank=True, null=True, upload_to='perfil_doador/%Y/%m/%d/')),
            ],
            options={
                'verbose_name_plural': 'Doadores',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id_endereco', models.AutoField(primary_key=True, serialize=False)),
                ('logradouro', models.CharField(max_length=100, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Numero_Contato',
            fields=[
                ('id_numero', models.AutoField(primary_key=True, serialize=False)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ong',
            fields=[
                ('id_ong', models.AutoField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=100, verbose_name='CNPJ')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Ong')),
                ('email_ong', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail da Ong')),
                ('senha', models.CharField(max_length=100)),
                ('imagem', models.FileField(blank=True, null=True, upload_to='perfil_ong/%Y/%m/%d/')),
                ('id_endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacoes.endereco')),
                ('id_numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacoes.numero_contato', verbose_name='Telefone de Contato')),
            ],
            options={
                'verbose_name_plural': 'Ongs',
            },
        ),
        migrations.CreateModel(
            name='Publicacao_Ong',
            fields=[
                ('id_publicacao_Ong', models.AutoField(primary_key=True, serialize=False)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='Publicacao_ong/%Y/%m/%d/')),
                ('categoria', models.CharField(choices=[('ROUPA', 'Roupa'), ('CALÇADO', 'Calçado'), ('ALIMENTO', 'Alimento'), ('MÓVEL', 'Móvel'), ('ELETRODOMÉSTICO', 'Eletrodoméstico'), ('EVENTO', 'Evento'), ('DOAÇÃO', 'Doação')], default='DOAÇÃO', max_length=20)),
                ('id_ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacoes.ong')),
            ],
            options={
                'verbose_name_plural': 'Publicações das Ongs',
            },
        ),
        migrations.CreateModel(
            name='Publicacao_Doador',
            fields=[
                ('id_publicacao_doador', models.AutoField(primary_key=True, serialize=False)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='Publicacao_doador/%Y/%m/%d/')),
                ('categoria', models.CharField(choices=[('ROUPA', 'Roupa'), ('CALÇADO', 'Calçado'), ('ALIMENTO', 'Alimento'), ('MÓVEL', 'Móvel'), ('ELETRODOMÉSTICO', 'Eletrodoméstico'), ('EVENTO', 'Evento'), ('DOAÇÃO', 'Doação')], default='DOAÇÃO', max_length=20)),
                ('id_doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacoes.doador')),
            ],
            options={
                'verbose_name_plural': 'Publicações dos Doadores',
            },
        ),
        migrations.AddField(
            model_name='doador',
            name='id_endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacoes.endereco'),
        ),
        migrations.AddField(
            model_name='doador',
            name='id_numero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacoes.numero_contato', verbose_name='Telefone de Contato'),
        ),
    ]
