# Generated by Django 3.1.2 on 2020-11-14 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='doador',
            name='id_endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacoes.endereco', verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='ong',
            name='id_endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacoes.endereco', verbose_name='Endereço'),
        ),
    ]
